on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Blazeboard/install-rust-substrate-action@v0.0.3-alpha
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: CommitBinaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "a@b.c"
          git config user.name "$GITHUB_ACTOR"
          git checkout master
          sudo git pull origin master
          sudo git add
          sudo git commit -m "[$GITHUB_WORKFLOW]Auto commit from Github Action"
          git remote set-url --push origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          git push origin master
